### PR TITLE
Update UI, fix visual bugs

### PR DESCRIPTION
**Pull request by nerbnerb**

### CODE REVIEW

**Comment by nerbnerb** [comment]
This is the GUI at this point:

**Comment by nerbnerb** [comment]
When scrolling list, the internship at the top might appear "cut off"

**Comment by nerbnerb** [comment]
All tags now have a tooltip on hover, displaying the full tag name.


Hovering on extra tag count will display tags not shown.

**Review by Marcusgwj — APPROVED** [review]
LGTM

**Pull request merged**
